### ISSUE TITLE
Customização de valor máximo de recursos e sugestões sobre o layout da ficha

### ISSUE THREAD

**Issue by paulobmedeiros** [mclemente/fvtt-tresdetv#1]
Não estou apontando um erro, mas uma sugestão de melhoria. Na ficha, seria interessante ter uma opção para customizar a fórmula dos recursos do personagem (PA, PV e PM). Já que algumas vantagens podem alterar o valor máximo desses recursos sem necessariamente alterar o atributo relacionado.

**Comment by paulobmedeiros** [comment]
Outro incomodo que notei foi que, ao acumular muitas vantagens, desvantagens, técnicas e itens, é necessário expandir a janela da ficha para continuar visualizando. Isso gera a possibilidade da janela chegar ao limite da tela, impedindo a visualização. No meu caso, que jogo em uma tela pequena, seria melhor se houvesse uma barra de rolagem.

Também gostaria de deixar o meu feedback em relação ao design da ficha de personagem. Acho que no geral está bem limpa e agradável, mas seguindo o problema que citei acima, com o tempo a ficha se tornando um pouco unilateral. O que quero dizer é que conforme acrescentamos itens a ficha, a maior parte das informações passa a ficar no lado direito da ficha, deixando o esquerdo meio vazio. Como sugestão, vou deixar uma montagem que eu fiz de como acho que ficaria melhor distribuído.

![image](https://github.com/mclemente/fvtt-tresdetv/assets/135181579/c54a1ba9-a69f-43af-a405-82b93c07dfce)

**Comment by mclemente** [comment]
> opção para customizar a fórmula dos recursos do personagem

Então, tecnicamente já tinha como modificador o multiplicador dos pontos, como mudar (PA x 5) para (PA x 6), mas só era acessível através de Efeitos Ativos, então não era muito útil para mudanças permanentes.

Adicionei a propriedade Bônus e agora ela adiciona ao Máximo dos pontos.
Tem um novo botão na barra superior da ficha para fazer estes ajustes.

> ficha

Movi as técnicas como você sugeriu.

Além disso, desde que saiu a ficha oficial eu planejava fazer umas mudanças na aparência dos Atributos e Pontos para deixar aquela seção ocupando menos espaço. Agora ela tem mais ou menos metade do tamanho da versão anterior.

Também inverti os pontos máximos e atuais para ficar semelhante à ficha oficial.
