### ISSUE TITLE
Iniciativa fora de ordem

### ISSUE THREAD

**Issue by Kabeleced06** [mclemente/fvtt-tresdetv#2]
Boa noite. 

Primeiro gostaria de agradecer imensamente pelo sistema, ta muito bom e só de pensar em jogar no roll20 já me dava calafrios, então muito obrigado por ter feito o sistema para o foundry.

Bom, a questão q trago aqui é que, após rolar a iniciativa, ela fica toda desorganizada, não da pra deixar na ordem certinha de nenhuma maneira. Não sei se é alguma configuração específica (olhei tudo e não achei uma solução). Desabilitei todos os módulos e não consegui resolver. No momento, acredito que possa ser algo do sistema. Se não for, já peço desculpas antecipadamente e se for, ficaria muito grato se pudesse ser resolvido. 

Desde já, agradeço a atenção.

**Comment by mclemente** [comment]
Estava bugado mesmo. É só atualizar que agora deve ficar organizado corretamente.

**Comment by Kabeleced06** [comment]
Nice, valeu mesmo!! Já baixei a atualização e está funcionando perfeitamente, valeu!
